

elt_data_pipeline_version_1:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'md:ev_analytics' 
      
      # Paste your long MotherDuck token here
      token: "{{ env_var('MOTHERDUCK_TOKEN') }}"

      # Keep these settings to help read the Google Cloud files
      filesystems:
        - fs: gcs
          token: ''
          project: 'your-gcp-project-id' # Optional but good to keep